### PR TITLE
Allow wildcards for matching except names

### PR DESCRIPTION
**Pull request by earthslasthope**

### CODE REVIEW

**Comment by OlehDutchenko** [comment]
Hi! Thanks for PR!
I will update npm package in few hours

**Comment by OlehDutchenko** [comment]
@earthslasthope sorry,
I update package on Monday.

**Comment by OlehDutchenko** [comment]
@earthslasthope already updated new npm version 1.2.0

**Comment by earthslasthope** [comment]
Awesome, thanks for the quick review and publish :)

**Pull request merged**
